services:
  sshd:
    image: lscr.io/linuxserver/openssh-server:9.9_p1-r2-ls190
    environment:
      - USER_NAME=demo
      - USER_PASSWORD=pass
      - PASSWORD_ACCESS=true

  sshpiper:
    build:
      context: ../..
      target: sshpiperd
      args:
        BUILDTAGS: full
    command:
      - /sshpiperd/plugins/username-router
    ports:
      - "2222:2222"
    depends_on:
      - sshd
